#!/usr/bin/env python3
"""
send_command.py — Standalone AC command sender for cron jobs.

Called by system cron. Reads ac_state.json at runtime for temp/mode/fan
so the cron entry never goes stale when you change AC settings.

Usage:
  send_command.py on  [--temp N] [--mode cool] [--fan auto] [--device 0]
  send_command.py off [--device 0]

Cron example (generated by cron_manager.py):
  30 22 * * * /home/user/.venv/bin/python3 /path/to/send_command.py on >> .../logs/cron.log 2>&1
"""

import argparse
import json
import logging
import sys
import time
from pathlib import Path

# ── Paths ─────────────────────────────────────────────────────────────────────
HERE     = Path(__file__).resolve().parent
LOG_DIR  = HERE / "logs"
LOG_DIR.mkdir(exist_ok=True)

# ── Logging: file + stdout (cron captures stdout via >> redirect) ──────────────
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [miraie_cron] %(levelname)s  %(message)s",
    datefmt="%Y-%m-%d %H:%M:%S",
    handlers=[
        logging.FileHandler(LOG_DIR / "cron.log"),
        logging.StreamHandler(sys.stdout),
    ],
)
log = logging.getLogger(__name__)

# Ensure miraie_scheduler is importable regardless of CWD
sys.path.insert(0, str(HERE))


# ── Helpers ───────────────────────────────────────────────────────────────────

def _load_ac_state() -> dict:
    """Read saved AC state (temp/mode/fan) from ac_state.json."""
    state_file = HERE / "ac_state.json"
    if state_file.exists():
        try:
            return json.loads(state_file.read_text())
        except Exception as exc:
            log.warning("Could not read ac_state.json: %s — using defaults", exc)
    return {"temp": 22, "mode": "cool", "fan": "auto"}


# ── Main ──────────────────────────────────────────────────────────────────────

def main() -> None:
    # Read saved state first so it can supply argparse defaults
    state = _load_ac_state()

    parser = argparse.ArgumentParser(
        description="Miraie AC command sender (cron-safe, reads ac_state.json by default)"
    )
    parser.add_argument("action", choices=["on", "off"],
                        help="Power state to send")
    parser.add_argument("--temp",   type=int,
                        default=state.get("temp", 22),
                        help="Target temperature °C — defaults to saved AC state")
    parser.add_argument("--mode",   default=state.get("mode", "cool"),
                        choices=["auto", "cool", "dry", "fan"],
                        help="AC mode — defaults to saved AC state")
    parser.add_argument("--fan",    default=state.get("fan", "auto"),
                        choices=["auto", "quiet", "low", "medium", "high"],
                        help="Fan speed — defaults to saved AC state")
    parser.add_argument("--device", type=int, default=0,
                        help="Device index (default: 0)")
    args = parser.parse_args()

    log.info("────────────────────────────────────────────────────")
    log.info("CRON_TRIGGER  action=%-3s  temp=%d°C  mode=%s  fan=%s  device=%d",
             args.action, args.temp, args.mode, args.fan, args.device)

    try:
        from miraie_scheduler import MiraieController, load_session

        session    = load_session()
        controller = MiraieController(session)
        controller.connect()
        controller.send(
            args.action,
            args.device,
            temp=args.temp,
            mode=args.mode,
            fan=args.fan,
        )
        time.sleep(1)           # let MQTT publish flush before disconnect
        controller.disconnect()
        log.info("SUCCESS ✓  command delivered")

    except FileNotFoundError as exc:
        log.error("FAILED — session file not found (%s). Run --setup first.", exc)
        sys.exit(1)
    except Exception as exc:
        log.error("FAILED — %s: %s", type(exc).__name__, exc)
        sys.exit(1)


if __name__ == "__main__":
    main()
